service: app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:167880115321:table/ItemTable
                
functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: get
  postItem:
    handler: src/lib/post/post-item.handler
    events:
      - http:
          path: /item
          method: post
  getItems:
    handler: src/lib/get/get-items.handler
    events:
      - http:
          path: /items
          method: get
  getItem:
    handler: src/lib/get/get-item.handler
    events:
      - http:
          path: /items/{id}
          method: get
  putItem:
    handler: src/lib/put/put-item.handler
    events:
      - http:
          path: /items/{id}
          method: put
resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ItemTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
